services:
  workspace:
    build:
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../
        target: /app
    tty: true
    privileged: true
    init: true
  db:
    image: mysql:8.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: template
      MYSQL_USER: app_user
      MYSQL_PASSWORD: passwd
    volumes:
      - ./.docker/db/data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci','--default-time-zone=+09:00', '--local-infile=1']
